language: node_js
node_js:
  - 6
env:
  - TEST_DIR=app
  - TEST_DIR=server
script: cd $TEST_DIR && npm install && npm test
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
